[package]
name = "solana-measure"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/solana-measure"
readme = "../README.md"
version = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
