[package]
version = "0.1.0"
name = "chess-script"
edition = "2021"

[dependencies]
sp1-sdk = {workspace = true}

[build-dependencies]
sp1-build = {workspace = true}

[target.'cfg(not(target_arch = "riscv32im-succinct-zkvm-elf"))'.dependencies]
tracing-appender = "0.2.3" 