[package]
version = "0.1.0"
name = "zk-svm-script"
edition = "2021"

[dependencies]
bincode = { workspace = true }
serde = { workspace = true }
solana-sdk = { workspace = true }
sp1-sdk = { workspace = true }
svm-runner = { workspace = true }

[build-dependencies]
sp1-build = { workspace = true }
